-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 09:51:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asistanceDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistanceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistanceDB` DEFAULT CHARACTER SET utf8 ;
USE `asistanceDB` ;

-- -----------------------------------------------------
-- Table `asistanceDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistanceDB`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(20) NULL,
  `user_surname` VARCHAR(25) NULL,
  `user_dni` VARCHAR(20) NULL,
  `user_password` VARCHAR(30) NULL,
  `user_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_dni_UNIQUE` (`user_dni` ASC),
  UNIQUE INDEX `user_mail_UNIQUE` (`user_mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistanceDB`.`user_assistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistanceDB`.`user_assistance` (
  `user_assistance_id` INT NOT NULL AUTO_INCREMENT,
  `user_delay` TINYINT(1) NULL,
  `user_absence` TINYINT(1) NULL,
  `user_time` DATETIME NULL,
  `user_min_time` DATETIME NULL,
  `user_max_time` DATETIME NULL,
  PRIMARY KEY (`user_assistance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistanceDB`.`user_count_absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistanceDB`.`user_count_absence` (
  `user_absence_id` INT NOT NULL,
  `user_absence_total` INT ZEROFILL NULL,
  PRIMARY KEY (`user_absence_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistanceDB`.`user_count_delay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistanceDB`.`user_count_delay` (
  `user_delay_id` INT NOT NULL,
  `user_delay_total` INT ZEROFILL NULL,
  PRIMARY KEY (`user_delay_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistanceDB`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistanceDB`.`user_type` (
  `user_type_id` INT NOT NULL,
  `user_type` TINYINT(1) ZEROFILL NOT NULL,
  `user_user_id` INT NOT NULL,
  `user_count_delay_user_delay_id` INT NOT NULL,
  `user_count_absence_user_absence_id` INT NOT NULL,
  `user_assistance_user_assistance_id` INT NOT NULL,
  PRIMARY KEY (`user_type_id`),
  INDEX `fk_user_type_user1_idx` (`user_user_id` ASC),
  INDEX `fk_user_type_user_count_delay1_idx` (`user_count_delay_user_delay_id` ASC),
  INDEX `fk_user_type_user_count_absence1_idx` (`user_count_absence_user_absence_id` ASC),
  INDEX `fk_user_type_user_assistance1_idx` (`user_assistance_user_assistance_id` ASC),
  CONSTRAINT `fk_user_type_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `asistanceDB`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user_count_delay1`
    FOREIGN KEY (`user_count_delay_user_delay_id`)
    REFERENCES `asistanceDB`.`user_count_delay` (`user_delay_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user_count_absence1`
    FOREIGN KEY (`user_count_absence_user_absence_id`)
    REFERENCES `asistanceDB`.`user_count_absence` (`user_absence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_user_assistance1`
    FOREIGN KEY (`user_assistance_user_assistance_id`)
    REFERENCES `asistanceDB`.`user_assistance` (`user_assistance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
